/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;
import model.bean.CadastroBEAN;

/**
 *
 * @author spd3
 */
public class VeiculosFrame extends javax.swing.JFrame {
    public static String marca;
    public static String modelo;
    public static String cor;
    public static String placa2;
    /**
     * Creates new form VeiculosFrame
     */
    public VeiculosFrame() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblModeloVeiculo = new javax.swing.JLabel();
        jtfModeloVeiculo = new javax.swing.JTextField();
        lblMarcaVeiculo = new javax.swing.JLabel();
        jtfCorVeiculo = new javax.swing.JTextField();
        lblCorVeiculo = new javax.swing.JLabel();
        jtfMarcaVeiculo = new javax.swing.JTextField();
        lblPlacaVeiculo = new javax.swing.JLabel();
        btnAssociarVeiculo = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        jtfPlacaVeiculo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Adicionar Veículo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblModeloVeiculo.setText("Modelo do Veículo:");
        jPanel1.add(lblModeloVeiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, -1, -1));

        jtfModeloVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfModeloVeiculoActionPerformed(evt);
            }
        });
        jPanel1.add(jtfModeloVeiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 120, -1));

        lblMarcaVeiculo.setText("Marca do Veículo:");
        jPanel1.add(lblMarcaVeiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));
        jPanel1.add(jtfCorVeiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, 120, -1));

        lblCorVeiculo.setText("Cor do veículo:");
        jPanel1.add(lblCorVeiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, -1, -1));
        jPanel1.add(jtfMarcaVeiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 120, -1));

        lblPlacaVeiculo.setText("Placa do Veículo:");
        jPanel1.add(lblPlacaVeiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, -1, -1));

        btnAssociarVeiculo.setText("Associar Veículo");
        btnAssociarVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssociarVeiculoActionPerformed(evt);
            }
        });
        jPanel1.add(btnAssociarVeiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, -1, -1));

        btnLimpar.setText("Limpar Campos");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, -1, -1));
        jPanel1.add(jtfPlacaVeiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, 110, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAssociarVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssociarVeiculoActionPerformed
        String placa = null;
        marca = null;
        modelo = null;
        cor = null;
        placa2 = null;
        
        if(jtfMarcaVeiculo.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "O campo Marca Veículo deve ser preenchido.");
            return;
        }else{
            marca = jtfMarcaVeiculo.getText().toUpperCase();
        }
        
        if(jtfModeloVeiculo.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "O campo Modelo Veículo deve ser preenchido.");
            return;
        }else{
            modelo = jtfModeloVeiculo.getText().toUpperCase();
        }
        
        if(jtfCorVeiculo.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "O campo Cor do Veículo deve ser preenchido.");
            return;
        }else{
            cor = jtfCorVeiculo.getText().toUpperCase();
        }
        
        placa = jtfPlacaVeiculo.getText().replaceAll("-", "");
        if(placa.equals("       ")){
            JOptionPane.showMessageDialog(null, "O campo Placa do Veículo deve ser preenchido.");
            return;
        }else{
            placa2 = jtfPlacaVeiculo.getText().toUpperCase();
        }
        this.dispose();
    }//GEN-LAST:event_btnAssociarVeiculoActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        jtfMarcaVeiculo.setText("");
        jtfModeloVeiculo.setText("");
        jtfCorVeiculo.setText("");
        jtfPlacaVeiculo.setText("");
    }//GEN-LAST:event_btnLimparActionPerformed

    private void jtfModeloVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfModeloVeiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfModeloVeiculoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VeiculosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VeiculosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VeiculosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VeiculosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VeiculosFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssociarVeiculo;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JTextField jtfCorVeiculo;
    public static javax.swing.JTextField jtfMarcaVeiculo;
    public static javax.swing.JTextField jtfModeloVeiculo;
    private javax.swing.JTextField jtfPlacaVeiculo;
    private javax.swing.JLabel lblCorVeiculo;
    private javax.swing.JLabel lblMarcaVeiculo;
    private javax.swing.JLabel lblModeloVeiculo;
    private javax.swing.JLabel lblPlacaVeiculo;
    // End of variables declaration//GEN-END:variables
}
