/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;
import model.bean.CadastroBEAN;

/**
 *
 * @author spd3
 */
public class VeiculosFrame extends javax.swing.JFrame {
    public static String marca;
    public static String modelo;
    public static String cor;
    public static String placa2;
    /**
     * Creates new form VeiculosFrame
     */
    public VeiculosFrame() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        modelo_veiculo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cor_veiculo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        marca_veiculo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        placa_veiculo = new javax.swing.JFormattedTextField();
        associar_veiculo = new javax.swing.JButton();
        limpar_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Adicionar Veículo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Modelo do Veículo:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, -1, -1));
        jPanel1.add(modelo_veiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 120, -1));

        jLabel2.setText("Marca do Veículo:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));
        jPanel1.add(cor_veiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 120, -1));

        jLabel3.setText("Cor do veículo:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, -1, -1));
        jPanel1.add(marca_veiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 120, -1));

        jLabel4.setText("Placa do Veículo:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, -1, -1));

        try {
            placa_veiculo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("???-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(placa_veiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, 100, -1));

        associar_veiculo.setText("Associar Veículo");
        associar_veiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                associar_veiculoActionPerformed(evt);
            }
        });
        jPanel1.add(associar_veiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(391, 80, -1, -1));

        limpar_button.setText("Limpar Campos");
        limpar_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpar_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(limpar_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 522, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void associar_veiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_associar_veiculoActionPerformed
        String placa = null;
        marca = null;
        modelo = null;
        cor = null;
        placa2 = null;
        
        if(marca_veiculo.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "O campo Marca Veículo deve ser preenchido.");
            return;
        }else{
            marca = marca_veiculo.getText().toUpperCase();
        }
        
        if(modelo_veiculo.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "O campo Modelo Veículo deve ser preenchido.");
            return;
        }else{
            modelo = modelo_veiculo.getText().toUpperCase();
        }
        
        if(cor_veiculo.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "O campo Cor do Veículo deve ser preenchido.");
            return;
        }else{
            cor = cor_veiculo.getText().toUpperCase();
        }
        
        placa = placa_veiculo.getText().replaceAll("-", "");
        if(placa.equals("       ")){
            JOptionPane.showMessageDialog(null, "O campo Placa do Veículo deve ser preenchido.");
            return;
        }else{
            placa2 = placa_veiculo.getText().toUpperCase();
        }
        this.dispose();
    }//GEN-LAST:event_associar_veiculoActionPerformed

    private void limpar_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpar_buttonActionPerformed
        marca_veiculo.setText("");
        modelo_veiculo.setText("");
        cor_veiculo.setText("");
        placa_veiculo.setText("");
    }//GEN-LAST:event_limpar_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VeiculosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VeiculosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VeiculosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VeiculosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VeiculosFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton associar_veiculo;
    public static javax.swing.JTextField cor_veiculo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton limpar_button;
    public static javax.swing.JTextField marca_veiculo;
    public static javax.swing.JTextField modelo_veiculo;
    public static javax.swing.JFormattedTextField placa_veiculo;
    // End of variables declaration//GEN-END:variables
}
